name: Build Kivy Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip wget openjdk-11-jdk python3-pip git build-essential

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK & Build-Tools
      run: |
        export ANDROIDSDK=$HOME/Android
        mkdir -p $ANDROIDSDK/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $ANDROIDSDK/cmdline-tools
        yes | $ANDROIDSDK/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROIDSDK \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"

    - name: Set environment variables for Buildozer
      run: |
        echo "export ANDROIDSDK=$HOME/Android" >> $GITHUB_ENV
        echo "export ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
        echo "export PATH=$HOME/Android/cmdline-tools/cmdline-tools/bin:$HOME/Android/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: trinkspiel-apk
        path: bin/*.apk
